### Base URL Configuration
@baseUrl = http://localhost:3000

### ========================================
### Basic Health Check
### ========================================

### Test server is running
GET {{baseUrl}}/
Accept: text/plain

### Original profile page
GET {{baseUrl}}/profile
Accept: text/plain

#read user
POST {{baseUrl}}/decode
Content-Type: application/json

{
  "id": "43b62dca-a5cb-485b-9800-166dd4bda377"
}